### ISSUE TITLE
Error in beforeMount hook: IntegrationError: Can only create one Element of type card.

### ISSUE THREAD

**Issue by benjaminkluegel** [fromAtoB/vue-stripe-elements#12] opened 2017-08-30 09:49 UTC
This happens when i leave and reenter the checkout route... any ideas?

"Error in beforeMount hook: "IntegrationError: Can only create one Element of type card."

**Comment by jasonlfunk** [comment] 2017-08-31 15:53
I'm having the same issue.

**Comment by nkoehring** [comment] 2017-08-31 18:54
better use `beforeCreate` then or use the components destroy hook to destroy the element

**Comment by jasonlfunk** [comment] 2017-09-01 05:47
It's not obvious to me how to destroy the element. It doesn't look like the component provides access to it. 

Shouldn't the component take care of that anyways? Am I not using the component correctly?

**Comment by rizr** [comment] 2017-09-03 22:09
+1

**Comment by Christilut** [comment] 2017-09-09 15:31
Same here, not sure how/if I can destroy it before HMR update but I would think the component is supposed to do that itself.

**Comment by sam3d** [comment] 2017-09-16 14:59
Any update on this?

**Comment by nkoehring** [comment] 2017-09-20 13:23
@sam3d @Christilut @rizr @benjaminkluegel A new version including @jasonlfunk's PR is published now. Thanks for you patience! Please know that the development now happens in my fork at [nkoehring/vue-stripe-elements](https://github.com/nkoehring/vue-stripe-elements.git)

**Comment by softbeehive** [comment] 2017-10-13 16:14
Closed by #14

**Closed by softbeehive** 2017-10-13 16:14 UTC

**Comment by safaorhan** [comment] 2018-09-14 21:51
Hello I'm getting the same error with version 0.2.9 as of today.

![screen shot 2018-09-15 at 00 50 52](https://user-images.githubusercontent.com/4990386/45576805-73ecf080-b881-11e8-9fa0-31d5bd9f7626.png)

**Comment by marcoT89** [comment] 2018-09-17 13:48
Same issue here. What is the workaround? I didn't get it...

**Comment by jbhamilton** [comment] 2018-10-10 17:32
Same #15 stated that it was fixed almost a year ago but it's still happening for me using v0.2.9

**Comment by danielcharrua** [comment] 2018-12-04 08:20
Building a SPA with two views that use the `Card` component I get the exact same error, any ideas or fix to this issue? Using v0.2.9

**Comment by danielcharrua** [comment] 2018-12-04 08:41
In my app I have three routes, let's say 1, 2 and 3.
2 and 3 use Card components and if I switch within these routes the error is shown, but if I click route number 1 in between those two routes, the error is not shown and it renders both routes as it should.
Any ideas?

**Comment by nachomozo** [comment] 2018-12-10 11:21
Same error here on hot reloading using 0.2.9

**Comment by vladislavkoz** [comment] 2019-01-30 15:42
You can add refs("SomeRef") to you component and then call in some function(like beforeDestroy() or some else) this.$refs.SomeRef.$destroy(). Profit)

**Comment by rcarcasses** [comment] 2019-05-03 14:49
@vladislavkoz it works, thanks!

**Comment by eckelarsson** [comment] 2019-06-13 12:23
Hade the same problem, but fixed it by doing this.

`let stripe = window.Stripe('pk_test_xxxxxxxxxxxx'),
    elements = stripe.elements(),
    card = undefined;

export default {
    name: 'Payment',
    mounted() {
      card = elements.create('card');
      card.mount(this.$refs.card);
    },
    beforeDestroy() {
      card.destroy(this.$refs.card);
    },
}`

**Comment by KentHawkings** [comment] 2019-06-27 11:12
This is still an issue for me on 0.2.10. Any word on getting this fixed?

**Comment by webdev778** [comment] 2019-06-29 03:15
I have same issue on 0.2.9

**Comment by perle-rare** [comment] 2019-11-18 12:21
@erdemtopak that mean you're not using the plugin since you're using directly the Stripe object, correct-me please if I'm wrong

i have the same issue with `"vue-stripe-elements-plus": "^0.3.0",`
thanks

**Comment by wheresrobert** [comment] 2020-02-01 23:48
For anyone that runs into this more recently:

This issue can come up if you use `v-if` and `v-cloak` together. If you do that, the DOM manipulation that happens will trigger this error. 

If you use `v-show` instead of `v-if`, it works fine. 

This ate like 8 hours of my business' time collectively.

**Comment by MrToxy** [comment] 2020-03-05 14:12
This is still happening and the fix by @eckelarsson doesn't really work for nuxt as the "createToken" function imported from the package errors out.

What's the reason behind not being able to create multiple card items and why was this closed with no apparent solution or fix?

**Comment by littlerzrz** [comment] 2020-12-07 02:11
For anyone using the vue-stripe plugin, just import the destroy method they created and destroy() directly in the beforeDestroy hook to destroy everything created for stripe. The plugin has already packed the method for us if you take a look at their source code.

**Comment by yusmar12** [comment] 2021-01-13 00:10
To me, it works with the `cardElement.destroy();` method

**Comment by aseidma** [comment] 2021-01-27 16:44
Another case of this happening is when using multiple payment methods with dynamic components together with `<keep-alive>`. Vue fails to destroy the old component on hot reload, which is how you might end up with two of the same components.

```
	<keep-alive>
		<component
			:is="selectedMethod"
			:elements="elements"
			:email="email"
			@set-payment="storePaymentInformation"
		/>
	</keep-alive>

// Computed property
	get selectedMethod() {
		const options: { [key: string]: any } = {
			card: Card,
			iban: Sepa,
		}

		return options[this.method]
	}
```

When the error is thrown, you can see the following thing happening using the Vue Dev Tools:
![Screenshot 2021-01-27 at 17 41 49](https://user-images.githubusercontent.com/40206670/106023427-13b01f80-60c7-11eb-9e59-efc54f32be88.png)

I don't know if this is a bug with Vue, Stripe or just intended behavior, but removing `<keep-alive>` does the trick and the error is gone.
